//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA_Advertisement
    {
        public int AdvertisementId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyPhone { get; set; }
        public string CompanyLogo { get; set; }
        public string CompanyQRCode { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string AdUrl { get; set; }
        public string AContent { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string AddUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
    }
}
