//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cu_Menu
    {
        public int MenuId { get; set; }
        public Nullable<int> FMenuId { get; set; }
        public string MenuName { get; set; }
        public Nullable<bool> IsBlank { get; set; }
        public string Imageicon { get; set; }
        public string URLAddress { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string AddUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
    }
}
