//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cu_User
    {
        public int UserId { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string UserPhone { get; set; }
        public string UserPassword { get; set; }
        public Nullable<bool> IsonLine { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string AddUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public string UserAuthority { get; set; }
        public Nullable<int> AuthorityId { get; set; }
        public Nullable<int> AgID { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<int> PageSize { get; set; }
    }
}
