//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cu_UserAuthority
    {
        public int AuthorityId { get; set; }
        public string Authority { get; set; }
        public string UserTypeName { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
