//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_CITYCALSS
    {
        public int ID { get; set; }
        public Nullable<int> KEYID { get; set; }
        public string NAME { get; set; }
        public string LETTER { get; set; }
        public Nullable<byte> SITETYPE { get; set; }
        public Nullable<int> SORT { get; set; }
        public string ENABLE { get; set; }
        public Nullable<System.DateTime> ENABLE_DATE { get; set; }
        public string HOT_FLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public string LAST_UPDATE_USER { get; set; }
        public int AREA_CODE { get; set; }
    }
}
