//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TZ_ExpandProject_View
    {
        public int ProjectId { get; set; }
        public Nullable<int> ProjectTypeId { get; set; }
        public string ActivityId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectTime { get; set; }
        public Nullable<decimal> ProjectPrice { get; set; }
        public string ProjectTripDays { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectSpecial { get; set; }
        public string ProjectPic { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> IsHot { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string AddUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public string ProjectTypeName { get; set; }
        public Nullable<int> UpCity { get; set; }
        public string ProjectDescription { get; set; }
        public string KeyWord { get; set; }
        public Nullable<int> SalesNum { get; set; }
        public Nullable<bool> IsWonderfulCase { get; set; }
        public Nullable<int> UpProjectId { get; set; }
        public string Company { get; set; }
        public string ProjectMinPic { get; set; }
        public string CityName { get; set; }
    }
}
